name: KingdomsAttributes
main: su.brim.kingdomsattributes.KingdomsAttributes
version: '${project.version}'
api-version: '1.21'
folia-supported: true

depend:
  - KingdomsAddon

description: Scale modifier for snow kingdom players

commands:
  kingdomsattributes:
    description: Управление плагином KingdomsAttributes
    usage: /<command> [reload]
    aliases: [kda]

permissions:
  kingdomsattributes.reload:
    description: Перезагрузка конфигурации
    default: op
